hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000

spring:
  sleuth:
    sampler:
      probability: 1